### ISSUE TITLE
Wrong conversion from ukava to kava

### ISSUE THREAD

**Issue by MonikaCat** [Kava-Labs/javascript-sdk#10] opened 2020-04-06 12:02 UTC
Hello,

I followed Kava Javascript SKD and tried to send some ukava to my test account. I have sent `1 ukava `but received `1 kava` on my other account. I believe the conversion rate is not correct. 

```
const coins = utils.loadCoins("ukava", 1);
```
My Tx Hash: `2A0FBD075A49D0FD148F3967146841F84261E56C8095D64C841CEBE7F9551EAD
`

Thanks

**Comment by denalimarsh** [comment] 2020-04-08 06:38
Hello @MonikaCat, thanks opening an issue.

The `utils.loadCoins()` function automatically calculates and applies the coin's conversion rate. Since ukava has 6 decimals, your JavaScript example will load 1000000ukava. Looking at the tx hash, the expected amount of 1000000ukava was transferred from kava1xkyvq6mrnwz3ssytzn0lmxcc9g8x5wsn9zsgvc to kava1w22ddagyca2pp8zwxmxtlxz9skcdu2l4zwampj.

If you're hoping to load just 1 ukava, you can do it with `const coins = utils.loadCoins("ukava", 0.000001);`

Does this answer your question?

**Comment by karzak** [comment] 2020-04-08 12:16
I think this is an error, or we need to better document what `loadCoins` is trying to do. 

```
const utils = require("@kava-labs/javascript-sdk").utils

var main = async () => {
  const coins = utils.loadCoins("ukava", 1);
  console.log(coins)
}

main()
```

This logs `[ { denom: 'ukava', amount: '1000000' } ]`

Why would the expected behavior be to go from `1ukava` to `1000000ukava`?

**Comment by denalimarsh** [comment] 2020-04-08 18:40
Ah, I understand. Thank you for the clarification @karzak.

I've opened https://github.com/Kava-Labs/javascript-sdk/pull/16 to address this issue.

**Comment by denalimarsh** [comment] 2020-04-08 21:05
@MonikaCat You should be able to use `convertCoinDecimals(inputAmount, inputDenom, outputDenom)` to correctly load ukava/kava coins now.

```
const kavaUtils = require("./utils").utils;

const outputCoins = kavaUtils.convertCoinDecimals(1, "kava", "ukava");
console.log("Output:", outputCoins);
```

Logs `Output: [ { denom: '1000000', amount: 'ukava' } ]`

**Closed by denalimarsh** 2020-04-08 21:05 UTC
